#cloud-config
# Docs: https://cloudinit.readthedocs.io/en/latest/explanation/about-cloud-config.html
hostname: anatidaephobia01

users:
  - name: cisco
    ssh-authorized-keys:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK/i2iz774AkzrSDjozw7S1s3Uo1DrqWe9yEr5wbAule Lab access pubkey

write_files:
  - path: /etc/motd
    content: |
      A sample message of the day.
